### PR TITLE
Fix/swipe to close

### LINKED ISSUE #289: Swipe to close does not work in Vue 2
### Reason

The swipe to close method is incompatible with Vue 2

### Description

The swipe to close gesture implemented, utilized a Vue 3 only library (vue3-touch-events). It had to be removed for Vue 2 compatibility. 

This library actually had 2 issues:
- It was incompatible with Vue 2
- It requires the customer to install and register the plugin outside the scope of our library. 

### Success Criteria

- [ ] swipe down gestures working in Vue 2
- [ ] swipe down gestures working in Vue 3
- [ ] swipe to close, only closes when swiping from the header down (otherwise it will break scrollables)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MiroBenicio**
# Issues Addressed

Closes #289 

## Additional Information

the design works with Vue native touch events, no need a library, but if we want to change these design, its necessary to find other way to do it

### CODE REVIEW

**Review by mike-audi — COMMENTED** [review]
@MiroBenicio the code looks good but let's have @timoguin test to make sure it functions as expected.

**Comment by timoguin** [comment]
@MiroBenicio currently I'm unable to build the app locally to be able to test this myself. In the meantime, could you upload a screen recording of it working?

**Comment by mike-audi** [comment]
> @MiroBenicio currently I'm unable to build the app locally to be able to test this myself. In the meantime, could you upload a screen recording of it working?

the swipe gesture can be quite finicky and needs testing on every screen before being merged in.

**Review by timoguin — APPROVED** [review]
Tested the Vue2 build of the app on a Pixel 7 Pro, and everything seems to be good.

(Screen recording shared in Discord)

**Pull request merged**
