### PR TITLE
Fix/imap and scanning warnings sheets

### LINKED ISSUE #229: [UI] Handle IMAP disabled warning
### Reason

If a user has IMAP disabled on their Gmail account, scan will raise an exception

### Description

Users must have IMAP enabled on their Gmail account for scans to work. If IMAP is disabled, Microblink will raise a specific IMAP exception. We need to catch this exception and make sure the user sees instructions on how to enable IMAP.

#### Wireframe

imap-error-screen

#### Instructions

Screenshot 2023-09-27 104810

### Success Criteria

- [ ] Gmail link should display as broken
- [ ] IMAP error is surfaced to the user
- [ ] User has clear instructions on how to enable IMAP
- [ ] User receives a push notification that there was an issue with email scanning

### Additional Information

- Gmail support article: https://support.google.com/mail/answer/7126229?hl=en#zippy=%2Cstep-check-that-imap-is-turned-on

### LINKED ISSUE #230: [UI] Create "long scan" dialog and push notification
### Reason

We need to inform the user the scans may take a long time and that they should leave the app open in the background

### Description

In order for scans to complete, the user must leave the app open (can be in background). We should display a dialog to the user letting them know how long scans can take and that they should leave the app open in the background.

Once scans have completed, we should send a push notification to the user to let them know they can close the app.

#### Wireframe

long-scan-screen

#### Notification Text

```
Receipt scanning complete! You can close the app!
```

### Success Criteria

- [ ] User is made aware that scans can take some time
- [ ] User receives a push notification when scans have completed

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MiroBenicio**
# Issues Addressed

Closes #229
Closes #230 

## Additional Information
sheets based on the actual wireframe and design

### CODE REVIEW

**Comment by mike-audi** [comment]
This PR simply need a UI/UX review before merge. 

@MiroBenicio can you post screenshots for @timoguin to review the language. I will take care of the formatting/stylizing

**Comment by MiroBenicio** [comment]
@timoguin 

image
image

**Comment by mike-audi** [comment]
okay. these screens are now pretty and formatted. 

@MiroBenicio & @timoguin — please decide on the language you want to use, update copy, and then merge. The code itself is good to go, the copy is not.

**Comment by timoguin** [comment]
Just tested the Vue2 build and had issues:

- The long scan screen never appears.
- The IMAP error screen never appears. (Assume this is related to the error not currently being cause in Android: https://github.com/tiki/capture-receipt-capacitor/issues/302)

I also experienced something similar to the issue reported here: https://github.com/tiki/apps-receipt-capacitor/issues/311

If you connect an email that has IMAP disabled, it shows no errors. However, if you close and reopen the app, that email account no longer shows in the list of accounts. I was able to reconnect the same account again.

**Comment by mike-audi** [comment]
> Just tested the Vue2 build and had issues:
> 
> * The long scan screen never appears.
> * The IMAP error screen never appears. (Assume this is related to the error not currently being cause in Android: [[Android] Catch the error when Gmail IMAP is disabled capture-receipt-capacitor#302](https://github.com/tiki/capture-receipt-capacitor/issues/302))
> 
> I also experienced something similar to the issue reported here: #311
> 
> If you connect an email that has IMAP disabled, it shows no errors. However, if you close and reopen the app, that email account no longer shows in the list of accounts. I was able to reconnect the same account again.

This story is just for the screens themselves, not the business logic. Those require additional and separate stories with clear logic & requirements.

**Review by mike-audi — APPROVED** [review]

**Comment by mike-audi** [comment]
@timoguin please note this is being merged in but the business logic is not implemented. Open stories with descriptions of how exactly you want the business logic to work and we will make these screens "show"

**Pull request merged**
