### PR TITLE
Fix: Change the theme colors

### LINKED ISSUE #197: [UI] Change the theme colors
### Reason

Change the main colors of the app according to the new design specification

### Description

needs to change the main button colors to fit the new design specification to rewards program pilot

### Success Criteria

- [ ] the theme colors fitting the design specification

### Additional Information

_No response_

### LINKED ISSUE #198: [UI] Change the offer screen text and bullets
### Reason

Fit the new design specification

### Description

Should update the bullet points of the offer screen to fit the new design specification and reward program

### Success Criteria

- [ ] the new bullet points fitting the new specification design

### Additional Information

_No response_

### LINKED ISSUE #199: [UI] Update the offer screen buttons
### Reason

fit the new design specification

### Description

Should add a close button in the corner of the sheet and move the learn more button to the new position

### Success Criteria

- [ ] buttons fitting the new design specification

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MiroBenicio**
Fix: update the offer screen buttons
Fix: Change the offer screen text and bullets

# Issues Addressed
Closes #197 
Closes #198 
Closes #199  

## Additional Information

Also changed the tiki config scope to the project dependencies instead of the example project

image
image

### CODE REVIEW

**Review by ricardobrg — CHANGES_REQUESTED** [review]
Rewards
- top padding
- text weight in all, except buttons
- offer card bottom padding

**Comment by MiroBenicio** [comment]
image 
image

**Review by ricardobrg — CHANGES_REQUESTED** [review]
Fix colors

**Comment by MiroBenicio** [comment]
@ricardobrg 

Captura de Tela 2023-09-25 às 13 52 48

**Review by ricardobrg — APPROVED** [review]

**Pull request merged**
